### PR TITLE
fix(cli): version edit wording to match aliases

### PR DESCRIPTION
**Pull request by lwander**
@ewiseblatt What do you think about this wording?

### CODE REVIEW

**Comment by ewiseblatt** [comment]
LGTM, except shouldnt there be an alias for the latest published patch
release for a given branch? I'd think you only care about specific versions
when rolling back.

**Comment by lwander** [comment]
I think it's best to wait before adding that behavior - it would mean updates will be applied to stable releases without the user explicitly asking for them - we could of course start publishing these aliases, but I think it might confuse/surprise users at first. WDYT, @jtk54?

**Comment by lwander** [comment]
For a little more context:

Halyard will either

1. complain with a warning that a new patch is out, or
2. prevent you from deploying an old version if we've explicitly made it "illegal"

**Comment by lwander** [comment]
So I think for now we have the tools in place to ensure users will be up-to-date on the latest patch version

**Comment by ewiseblatt** [comment]
ok

**Comment by jtk54** [comment]
I think we should avoid doing implicit things until users are familiar with what is going on with Halyard.

**Comment by ewiseblatt** [comment]
I think it should be easy to do the things we want them to be doing.

**Comment by lwander** [comment]
Agreed, let's figure out how best to do that. Maybe the alias should instead by `1.4.*` or something to be clear you're matching the latest patch always.

**Pull request merged**
