### PR TITLE
update(kubectl): Update dockerfile to use latest kubectl available

### PR DESCRIPTION
**Pull request by ricklagerweij**
Update kubectl to latest current version available.

### CODE REVIEW

**Comment by jfillo** [comment]
@ricklagerweij @ezimanyi can we get this PR moved along? Currently Halyard cannot deploy Spinnaker to new k8s 1.14 clusters because the kubectl binary is so old.

**Comment by ezimanyi** [comment]
I'm happy to re-review this after the changes, or a new equivalent PR

**Comment by jfillo** [comment]
Sounds good. If @ricklagerweij doesn't get to it. I will tomorrow

**Comment by ezimanyi** [comment]
Superseded by #1270

**Pull request closed without merging**
