### PR TITLE
fix(deploy): Copy file metadata to custom profiles

### PR DESCRIPTION
**Pull request by lwander**

### CODE REVIEW

**Comment by cristim** [comment]
Just an into this as well.

Was this fix released already? How to make use of it?

**Comment by lwander** [comment]
You can if you're up for using the nightly install of Halyard, what was your install path?

**Comment by cristim** [comment]
@lwander I use the Docker halyard image.

**Comment by lwander** [comment]
If you pull `:nightly` you should see this fix

**Comment by cristim** [comment]
Thanks!

**Comment by cristim** [comment]
It doesn't seem to work, the Kubernetes pod is missing all the content of /opt/deck/html as soon as the changed settings.js is deployed:

```
# ls -la /opt/deck/html                                                                               
total 0
drwxrwxrwt 3 www-data root 100 Aug  8 15:25 .
drwxr-xr-x 1 root     root  67 Aug  8 15:25 ..
drwxr-xr-x 2 www-data root  60 Aug  8 15:25 ..8988_08_08_15_25_03.760686059
lrwxrwxrwx 1 www-data root  31 Aug  8 15:25 ..data -> ..8988_08_08_15_25_03.760686059
lrwxrwxrwx 1 www-data root  18 Aug  8 15:25 settings.js -> ..data/settings.js
```

I extracted this from the apache log, which complains about the missing index.html and returns a 403:
```
[Tue Aug 08 15:58:30.163804 2017] [authz_core:debug] [pid 4212:tid 140059814586112] mod_authz_core.c(809): [client 100.109.113.64:32830] AH01626: authorization result of Require all granted: granted
[Tue Aug 08 15:58:30.163839 2017] [authz_core:debug] [pid 4212:tid 140059814586112] mod_authz_core.c(809): [client 100.109.113.64:32830] AH01626: authorization result of <RequireAny>: granted
[Tue Aug 08 15:58:30.163938 2017] [autoindex:error] [pid 4212:tid 140059814586112] [client 100.109.113.64:32830] AH01276: Cannot serve directory /opt/deck/html/: No matching DirectoryIndex (index.html,index.cgi,index.pl,index.php,index.xhtml,index.htm) found, and server-generated directory index forbidden by Options directive
```

On a previous (working) pod I had a lot of files in there:
```
root@spin-deck-v009-l9xs5:/opt/deck# ls -la /opt/deck/html/
total 23356
drwxr-xr-x 1 root root      25 Jul 27 15:17 .
drwxr-xr-x 1 root root      79 Aug  8 15:59 ..
-rw-r--r-- 1 root root   37971 Jul 27 15:16 0302f9a517622b02ca8abb145c33cb16.png
-rw-r--r-- 1 root root  238112 Jul 27 15:16 0531f249a07d5403d114be348312494c.otf
-rw-r--r-- 1 root root   82472 Jul 27 15:16 0904e4449d125c5a47cec5e8f7436186.otf
-rw-r--r-- 1 root root   16238 Jul 27 15:16 0c26b138acc338c113328ae128cacc2b.png
-rw-r--r-- 1 root root  104482 Jul 27 15:16 0d91dad620259787179d6fc9168aef65.eot
-rw-r--r-- 1 root root  230688 Jul 27 15:16 111fe8b7e2dbe4f68eabf313a7c07d98.otf
-rw-r--r-- 1 root root   78704 Jul 27 15:16 1574d1389749e3744314ece88cceb168.otf
-rw-r--r-- 1 root root   54260 Jul 27 15:16 178e79322ccaa80916919737b861e3c9.woff
-rw-r--r-- 1 root root  291584 Jul 27 15:16 2599a39a18b9726c611d815dffbba4bc.ttf
-rw-r--r-- 1 root root  293960 Jul 27 15:16 26add37c629cf15955b71bcb5efb2e02.ttf
-rw-r--r-- 1 root root  103620 Jul 27 15:16 29bb28f7c90cd7dfb7a09c4561ca271e.ttf
-rw-r--r-- 1 root root     613 Jul 27 15:16 2ca61b76e22053571dd8611e5aac4900.png
-rw-r--r-- 1 root root   28482 Jul 27 15:16 36f6c951efe9a52aec660e6597bf3328.svg
-rw-r--r-- 1 root root  293304 Jul 27 15:16 39b40cfcb316df61a5a9e48d29db74d0.ttf
-rw-r--r-- 1 root root  135828 Jul 27 15:16 3bfca25c56db239ceab5a0c4940f1f24.woff
-rw-r--r-- 1 root root   10103 Jul 27 15:16 3fde08759da2a1841abc8da2397c82fc.svg
-rw-r--r-- 1 root root  292794 Jul 27 15:16 4019cd70f5908d5fdbecd716959fcf50.eot
-rw-r--r-- 1 root root  238044 Jul 27 15:16 411cd2257bbdd1587b14d277934fdbbe.otf
-rw-r--r-- 1 root root   18028 Jul 27 15:16 448c34a56d699c29117adc64c43affeb.woff2
-rw-r--r-- 1 root root  289854 Jul 27 15:16 4838df6177f11aa004692c3dfc204c31.eot
-rw-r--r-- 1 root root  129732 Jul 27 15:16 488b68e155537cf13d2c3af5200b359a.woff
-rw-r--r-- 1 root root     845 Jul 27 15:16 49e3f006018662f60f1db2aec0b2cca9.png
-rw-r--r-- 1 root root  103686 Jul 27 15:16 4c9d790f1e883aa315121793c771db8f.eot
-rw-r--r-- 1 root root  111585 Jul 27 15:16 4ffafafa20fe63f1d4bd28e332093b06.svg
-rw-r--r-- 1 root root    7361 Jul 27 15:16 50336445f216074c4bf58fcf4e43b784.png
-rw-r--r-- 1 root root  291994 Jul 27 15:16 52d598098bb11d6a98573f2bae4f8468.eot
-rw-r--r-- 1 root root    2124 Jul 27 15:16 5674c43f0f4426c6c76fb70aadb83871.eot
-rw-r--r-- 1 root root  289528 Jul 27 15:16 60a663ad325c6559e17071430e18525a.ttf
-rw-r--r-- 1 root root   52320 Jul 27 15:16 6608f02dd314d9881eb719d8834acc8d.woff
-rw-r--r-- 1 root root  165742 Jul 27 15:16 674f50d287a8c48dc19ba404d20fe713.eot
-rw-r--r-- 1 root root  104334 Jul 27 15:16 6b1b85286afd14fcc330340543c720df.eot
-rw-r--r-- 1 root root  133352 Jul 27 15:16 788a2bcde2b05619551257e5f2053278.woff
-rw-r--r-- 1 root root  134540 Jul 27 15:16 7a89c69cdc383fe3ac47a5e4281e8f92.woff
-rw-r--r-- 1 root root    1849 Jul 27 15:16 7b9776076d5fceef4993b55c9383dedd.gif
-rw-r--r-- 1 root root   11274 Jul 27 15:16 7f70bd91558a2a062aa6fe12a8e06039.png
-rw-r--r-- 1 root root  132224 Jul 27 15:16 80391e3815cfff1f2ee1024e9db5dd88.woff
-rw-r--r-- 1 root root  294262 Jul 27 15:16 82c5611d313a5d5be72897c7ef59f95e.eot
-rw-r--r-- 1 root root    2258 Jul 27 15:16 83ca4a7afb4862e5fc4a01c86c59e6a3.svg
-rw-r--r-- 1 root root  103996 Jul 27 15:16 855d27d4302ff2af2f282f84324157a8.ttf
-rw-r--r-- 1 root root  108738 Jul 27 15:16 89889688147bd7575d6327160d64e760.svg
-rw-r--r-- 1 root root  291648 Jul 27 15:16 8bfca62e77587ee0f2dd3c06d76c7bf8.ttf
-rw-r--r-- 1 root root  291890 Jul 27 15:16 8e3f84f3b184897b1cbe5dea2a86e78c.eot
-rw-r--r-- 1 root root   79728 Jul 27 15:16 90c1bb00254c180f62a46cc5a13c4f51.otf
-rw-r--r-- 1 root root  444379 Jul 27 15:16 912ec66d7572ff821749319396470bde.svg
-rw-r--r-- 1 root root    3792 Jul 27 15:16 92a2fcf6104437cd202782fca687ab00.svg
-rw-r--r-- 1 root root  234960 Jul 27 15:16 9ba6f592e924057c6e9746649e9a15aa.otf
-rw-r--r-- 1 root root  103008 Jul 27 15:16 9baa9f9d98028f380c202e833863745e.ttf
-rw-r--r-- 1 root root    1960 Jul 27 15:16 a0486faf6307c12ed540ba65308403bf.ttf
-rw-r--r-- 1 root root     634 Jul 27 15:16 a1be69bf0d19c2458964a10f19cc50d9.svg
-rw-r--r-- 1 root root   54292 Jul 27 15:16 a83b890e7a2a99d546287478b1d55c30.woff
-rw-r--r-- 1 root root   77160 Jul 27 15:16 af7ae505a9eed503f8b8e6982036873e.woff2
-rw-r--r-- 1 root root 7438264 Jul 27 15:16 app.js
-rw-r--r-- 1 root root  165548 Jul 27 15:16 b06871f281fee6b241d60582ae9369b9.ttf
-rw-r--r-- 1 root root  103342 Jul 27 15:16 b35af156ddaef6f7e2c0110ebf7fae8f.eot
-rw-r--r-- 1 root root   83512 Jul 27 15:16 b580cee3df9442d9b5ae8a95d0266631.otf
-rw-r--r-- 1 root root   50064 Jul 27 15:16 bd14278c5a4f83cd5a87e0750aa7167d.woff
-rw-r--r-- 1 root root  292456 Jul 27 15:16 bef69c3aefd6ca9f4ed6e03cfa83d117.ttf
-rw-r--r-- 1 root root  103094 Jul 27 15:16 befd8cf046e763b665cab0a5ade929a3.eot
-rw-r--r-- 1 root root   81672 Jul 27 15:16 c00459cbfaaa45b881cf7b9e87ec5d8a.otf
-rw-r--r-- 1 root root   17659 Jul 27 15:16 c11701b435884a3d689806aaa9fb81d1.svg
-rw-r--r-- 1 root root  103336 Jul 27 15:16 c5430f5405a479e6dac1431f8ca7160f.ttf
-rw-r--r-- 1 root root   54204 Jul 27 15:16 c563ef31d26c5f9598e8e95d1d3b7e3f.woff
-rw-r--r-- 1 root root    2924 Jul 27 15:16 cc1cc28496ce8851644d8dff31ef150a.svg
-rw-r--r-- 1 root root    2551 Jul 27 15:16 d44e5f78738306f8d064b31a7a43c14d.svg
-rw-r--r-- 1 root root  103934 Jul 27 15:16 d488c16f2d1f790920b4b8377aa4a8e3.eot
-rw-r--r-- 1 root root   53852 Jul 27 15:16 d9957303d12ebd80115b931696b05ed3.woff
-rw-r--r-- 1 root root   45404 Jul 27 15:16 e18bbf611f2a2e43afc071aa2f4e1512.ttf
-rw-r--r-- 1 root root  239148 Jul 27 15:16 e2cac00e5cefaab56188ecc30cb1f990.otf
-rw-r--r-- 1 root root   82620 Jul 27 15:16 e430ca7e1bf571be5143e8ea6f3e956c.otf
-rw-r--r-- 1 root root  293630 Jul 27 15:16 e573bb40138e45b04a9a4c47508d37db.eot
-rw-r--r-- 1 root root  102756 Jul 27 15:16 e63a68bc9ffb55e121f386de1da4b7ab.ttf
-rw-r--r-- 1 root root  104124 Jul 27 15:16 ef10cbbe74965d35bc56e5d191c6c7e1.ttf
-rw-r--r-- 1 root root  124560 Jul 27 15:16 f2558c5a9e8fb9d3c022c6d27a62a239.woff
-rw-r--r-- 1 root root    2036 Jul 27 15:16 f28c7ac1dbc396dc02ae471017f2279e.woff
-rw-r--r-- 1 root root   20127 Jul 27 15:16 f4769f9bdb7466be65088239c12046d1.eot
-rw-r--r-- 1 root root    9112 Jul 27 15:16 f53f2c5d4ead91e085fa2c939c11fabc.png
-rw-r--r-- 1 root root  226624 Jul 27 15:16 f99485faea565127141abae8a99f389b.otf
-rw-r--r-- 1 root root   23424 Jul 27 15:16 fa2772327f55d8198301fdb8bcfc8158.woff
-rw-r--r-- 1 root root   15086 Jul 27 15:16 favicon.ico
-rw-r--r-- 1 root root   98024 Jul 27 15:16 fee66e712a8a08eef5805a46892932ad.woff
-rw-r--r-- 1 root root    5956 Jul 27 15:16 index.html
-rw-r--r-- 1 root root    5850 Jul 27 15:16 init.js
-rw-r--r-- 1 root root    3426 Aug  8 15:59 settings.js
-rw-r--r-- 1 root root 7063061 Jul 27 15:16 vendor.bundle.js
-rw-r--r-- 1 root root      54 Jul 27 15:12 version.json
```

**Comment by lwander** [comment]
This is an unrelated issue that has to do with how settings.js is mounted

**Pull request merged**
