### PR TITLE
Update commands.md

### PR DESCRIPTION
**Pull request by jasonmcintosh**
Added extra description around metrics-stores being tied to only spinnaker metrics and not for canaries.  @duftler Here ya go :)   HOPE this clarifies things for others.

### CODE REVIEW

**Comment by lwander** [comment]
These need to be updated in the CLI, these docs are autogenerated

**Comment by duftler** [comment]
My mistake, should have read more carefully. I'll fix it.

**Comment by duftler** [comment]
https://github.com/spinnaker/halyard/pull/947

**Comment by jasonmcintosh** [comment]
DOH - my bad :)  I was in a rush myself and missed it thanks @lwander

**Pull request merged**
