### PR TITLE
feat(Artifactory Search): Add new search fields to support multiple reps

### PR DESCRIPTION
**Pull request by sirigithub**
Co-authored-by: Jonathan Haeden<Jonathan.haeden@outlook.com

This feature has been raised to enhance the Artifactory search configuration used by Artifactory trigger to support multiple repos like Maven, Helm charts. This new  field will let the user specify the type of repo they would like to configure for each search.

The code updates  include the new fields
```java
private String repoType;
``` 
A search configuration would look like 
```yaml
searches:
  - name: test-helm
    permissions: {}
    baseUrl: https://artifactory-url/artifactory
    repo: test-helm-local
    repoType: helm
    username: username
    password: ..
  - name: test-maven
    permissions: {}
    baseUrl: https://artifactory-url/artifactory
    repo: test-maven-local
    groupId: com.mycompany
    searchPattern: pom
    username:
```
Referenced feature request: https://github.com/spinnaker/spinnaker/issues/5074
Reference of pull request in igor for enhancements to ArtifactorySearch.java: https://github.com/spinnaker/igor/pull/556

### CODE REVIEW

**Comment by robzienert** [comment]
I have no idea if this is all that's necessary to add support for a new config field. 🤷‍♂ @ezimanyi I could use a quick eyeball & maybe a small education so I can help you review a tad.

**Comment by ezimanyi** [comment]
This should be all that's necessary to be able to read that field in the `hal` config and pass it through to the igor config (as all the code doing that is operating on the `ArtifactorySearch` object and just serializing/deserializing it).

This change will *not* add parameters to the relevant `hal config repository artifactory ...` commands so that you can use the CLI to edit this field.  If you'd like to do that, you can see the change that originally added these commands in #1288.

Either way, I'd like @Jammy-Louie to review as he added artifactory support to Halyard.

**Comment by sirigithub** [comment]
Thank you @ezimanyi , I will go through the initial commit to check the changes needed to introduce a new field via hal CLI.

**Comment by ryu1kn** [comment]
@Jammy-Louie As Helm repos don't need `--groupId`, we change the logic to conditionally check the existence.

**Comment by Jammy-Louie** [comment]
LGTM seems like everythin is set properly.

question, are we only handling helm and maven repo types for now?

**Pull request merged**
