### PR TITLE
feat(config/secrets): add SecretSession and SecretSessionManager

### PR DESCRIPTION
**Pull request by KathrynLewis**
Part of secrets management project. 

Note: these classes will require the korkSecrets dependency in order to build.

[spinnaker/spinnaker#3649](https://github.com/spinnaker/spinnaker/issues/3649)

### CODE REVIEW

**Comment by lwander** [comment]
QQ: why put these in halyard rather than kork? As I understand it, these will be used by both the services & halyard where appropriate.

**Comment by ncknt** [comment]
@lwander This adds caching and secret file tracking. The thought was that Halyard will need to decrypt the same thing multiple times whereas services may not. That was before learning about `archaius` which seems to check the config multiple times. So we've added caching to `kork/SecretManager` as well (not in a PR yet). Let us clean that up.

**Comment by KathrynLewis** [comment]
@lwander We've moved the caching into the SecretManager class in kork. See [this PR](https://github.com/spinnaker/kork/pull/225). The update here depends on that PR being merged. Let me know if anything else should be changed here. Thanks!

**Comment by lwander** [comment]
LGTM, you may need to rebase to force a rebuild against the current HEAD

**Pull request merged**
