### PR TITLE
fix(deploy): Remove groupmembership from bootstrapping account

### PR DESCRIPTION
**Pull request by lwander**
This change only manifests itself on the bootstrapping clouddriver.

### CODE REVIEW

**Comment by ttomsu** [comment]
Lgtm

**Comment by idoshamun** [comment]
Thanks! When will it be available?

**Comment by lwander** [comment]
It was built last night, so in the nightly release track version 1.13.0-345
should have it.

**Comment by idoshamun** [comment]
I'll give it a try!

**Comment by idoshamun** [comment]
I still get 403 when trying to deploying but this time `ERROR Failed to monitor task: 403 Forbidden`

**Comment by lwander** [comment]
For the k8s account being deployed to - do you see any `requiredGroupMemberships` set under `~/.hal-staging/clouddriver-bootstrap.yml`?

**Comment by lwander** [comment]
@ttomsu we checked offline that there are no required group memberships for that account - what would cause the 403?

**Comment by lwander** [comment]
Maybe fiat hasn't picked up the changes yet, we're trying the deploy again. If that fixes it, clouddriver should push group membership changes on startup to fiat.

**Pull request merged**
