### PR TITLE
[issues/3249] expose sidecar ports

### PR DESCRIPTION
**Pull request by jfillo**
This PR is to address the feature request I submitted originally submitted at:
https://github.com/spinnaker/spinnaker/issues/3249

### CODE REVIEW

**Comment by jfillo** [comment]
Since the type of Service definition is of ClusterIP the scope of access to the monitoring ports would be to whatever other services are running on the same k8s cluster as the spinnaker installation, correct?

**Comment by kskewes** [comment]
We could call out the potentially sensitive nature and lack of auth on monitoring endpoints if exposed.
Direct potential users to consider at a minimum L4+ network level methods such as Kubernetes network policies, reverse proxy (per Prometheus stance), etc.

Is the alternative to leverage existing auth mechanisms on monitoring endpoints and require users to configure x509 or similar service accounts for Prometheus? Not sure how much work this would be...

**Comment by lwander** [comment]
Maybe there's a network policy we can deploy that limits access to prometheus? Or, at the very least recommend one if it's too hard to guess what the network policy should enforce?

**Comment by kskewes** [comment]
Sure. Example Network policy for kube-prometheus below.
Requires Kubernetes v1.11 to combine both pod and namespace selectors.
Remove one selector (pod or namespace) if on Kubernetes

```
---
# Allow Prometheus Monitoring Scraping
# Requires v1.11. For earlier Kubernetes versions remove either namespaceSelector or podSelector
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-prometheus-scrape
  namespace: spinnaker
spec:
  podSelector:
    matchLabels:
      app: spin
  ingress:
  - ports:
    - port: 8008
    from:
    - namespaceSelector: # Prometheus namespace
        matchLabels:
          name: monitoring
      podSelector:     # Prometheus pods
        matchLabels:
          app: prometheus
```

Note I'm exposing 8008 with a duplicate service in Spinnaker namespace for testing. With the above PR the endpoint to test would be something like `spin-clouddriver.spinnaker:8008/prometheus_metrics`.

**Test without policy:**
```
/prometheus $ wget spin-clouddriver-monitoring.spinnaker:8008/prometheus_metrics
Connecting to spin-clouddriver-monitoring.spinnaker:8008 (172.21.1.54:8008)

wget: can't connect to remote host (172.21.1.54): Connection timed out
```
**Test with policy:**
```
/prometheus $ wget spin-clouddriver-monitoring.spinnaker:8008/prometheus_metrics
Connecting to spin-clouddriver-monitoring.spinnaker:8008 (172.21.1.54:8008)
prometheus_metrics   100% |*****************************************************************************************************************************************|   372k  0:00:00 ETA
```

**Comment by kevinawoo** [comment]
Hey all, this is a pretty old PR, so I'm going play janitor 🧹 and just close it for now. 

Feel free to create a new PR and we'll take a look again with a new set of eyes 👀 !

**Pull request closed without merging**
