### PR TITLE
feature(ci/gitlab): Add support for GitLab CI

### PR DESCRIPTION
**Pull request by abergmeier**
These are the proposed changes for getting GitLab CI support into Halyard.
Comments very welcome.

**DO NOT MERGE**

### CODE REVIEW

**Comment by abergmeier** [comment]
If someone has a great way of getting tests into place for this, shoot please.

**Comment by ezimanyi** [comment]
@abergmeier : Is this ready for merge?  If so, I'm happy to merge it---just let me know!  Thanks!

**Comment by opedroso** [comment]
I agree with lwander comment on the testing front.
I did notice that only "gitlab add" and "gitlab edit" commands are being added.
Are "gitlab list" and "gitlab delete" automatically provided?
I am new to the codebase, so don't know enough. But I am normally dependent on list and delete to fix setup mix-ups...

**Comment by diasjorge** [comment]
any way to move this PR forward?

**Comment by ezimanyi** [comment]
Closing due to age; please re-open if you start working on this again.

**Pull request closed without merging**
