### PR TITLE
Count docker tags rather than ping v2 endpoint

### PR DESCRIPTION
**Pull request by lwander**

### CODE REVIEW

**Comment by judy** [comment]
Tested against an AWS ECR registry. I couldn't validate my credentials before this change, and can validate after this change. +1

**Comment by lwander** [comment]
Sweet, is it showing any new warnings? I'm worried it won't pick up on tags in your provided repos even though they've been supplied.

**Comment by lwander** [comment]
The command you posted in slack verifies this. Thanks!

**Comment by judy** [comment]
Nope, no new warnings! Just the expected success output.

**Pull request merged**
