### PR TITLE
feat(stats): Adds Telemetry validator, which prints a new Info level …

### PR DESCRIPTION
**Pull request by ttomsu**
…message that will get printed during all `hal config telemetry enable|disable` and `hal deploy apply` invocations. Samples below:

```
$ hal config telemetry enable
+ Get current deployment
  Success
+ Enable or disable telemetry
  Success
Validation in default.telemetry:
- INFO Telemetry is currently ENABLED. Usage statistics are being
  collected—Thank you!These stats inform improvements to the product, and that
  helps the community.To disable, run `hal config telemetry disable`.To learn more
  about what and how telemetry data is used, please see
  https://www.spinnaker.io/community/stats

+ Successfully enabled telemetry settings.

```

```
$ hal config telemetry disable
+ Get current deployment
  Success
+ Enable or disable telemetry
  Success
Validation in default.telemetry:
- INFO Telemetry is currently DISABLED. Usage statistics are not
  being collected. Please consider enabling statistic collection. These stats
  inform improvements to the product, and that helps the community. To enable, run
  `hal config telemetry enable`. To learn more about what and how telemetry data
  is used, please see https://www.spinnaker.io/community/stats.

+ Successfully disabled telemetry settings.

```

I realize this kind of repurposes the `Problem` and `ProblemSet` classes to print an info message, but the infrastructure is super useful for this kind of task, i.e. only print a message during specific commands. Renaming all instances of Problem and ProblemSet would blow up this PR and mask what is actually trying to be accomplished.

### CODE REVIEW

**Comment by demobox** [comment]
> hal config telemetry enable

Perhaps `hal config stats enable`?

/cc @dorbin

**Comment by ttomsu** [comment]
Changing from `stats` to `telemetry` is a much bigger change, and one I'm not a big fan of - telemetry is more semantically accurate at the point of collection, and they're turned into stats on the backend by analysis. 

That being said, I realize we use the term interchangeably through the codebase, and I would prefer to use one term.

**Comment by dorbin** [comment]
@ttomsu , @demobox 
I have  no opinion on "stats" v. "telemetry." Either is ok with me.

**Comment by ttomsu** [comment]
Since changing the wording is out of scope for this PR, I'll merge as is and we can bikeshed on it in another PR.

**Pull request merged**
