### PR TITLE
Add example for jenkins configuration

### PR DESCRIPTION
**Pull request by gardleopard**
@lwander I do not know if this is something you want. Just wanted to give you an example on what I would like to have included in the documentation.

### CODE REVIEW

**Comment by lwander** [comment]
These docs are auto-generated, so a better place to put this would be in the commands description field.

**Comment by gardleopard** [comment]
@lwander how do you generate the docs?

**Comment by lwander** [comment]
run `make` in the `halyard-cli` directory

**Comment by lwander** [comment]
hey @gardleopard I'm going to close this since this type of instruction is a better fit for the new docs site spinnaker.github.io that we're slowly building out.

**Pull request closed without merging**
