### PR TITLE
feat(localgit): Add --prep-only flag to just clone repos.

### PR DESCRIPTION
**Pull request by duftler**
Didn't bother to add the `--stage-only` flag to `ApplyDeployCommand` yet.

WDYT of the approach? Options include:

1) Go with what's here.
2) Contain the `stageOnly` checks to just `ApplyDeployCommand`. This will result in the repo's still being cloned, but no files will be generated in `~/.hal/default/staging`.
3) Decide it's too messy and not worth it and abandon it.

### CODE REVIEW

**Comment by lwander** [comment]
This might get a little confusing, since only the local git, debian & bake deployments really make use of that remote action. Everything else completes their deployment before that script is sent back to the user.

**Comment by duftler** [comment]
Yup, I agree; so (1) is out. That leaves (2) or (3).

**Comment by lwander** [comment]
Do you think 2 is worth it? Maybe there is some happy alternate path that creates the config as a separate command.

**Comment by brandonnelson3** [comment]
I agree. I think 2 is easy enough to just knock out. If it starts to get out of hand then maybe reconsider but I think it will likely be reasonable.

**Comment by duftler** [comment]
Updated to just do the cloning for now. PTAL.

**Comment by duftler** [comment]
ping

**Pull request merged**
