### PR TITLE
feat(jenkins): Support for  overriding TrustStore used by Jenkins (#363)

### PR DESCRIPTION
**Pull request by sergedonaldp**
Adding missing support for Halyard as discussed with @ezimanyi  on Slack.

### CODE REVIEW

**Comment by ezimanyi** [comment]
And I just noticed this is a PR against the 1.18.x branch.  As this is really a feature, we'd generally want to merge this into `master` and release with the next major release.  (And even in cases where there's a bug fix, we generally merge into `master` first then cherry-pick into the release.)  Do you mind moving this to be a PR against the `master` branch?  Thanks!

**Comment by sergedonaldp** [comment]
> And I just noticed this is a PR against the 1.18.x branch. As this is really a feature, we'd generally want to merge this into `master` and release with the next major release. (And even in cases where there's a bug fix, we generally merge into `master` first then cherry-pick into the release.) Do you mind moving this to be a PR against the `master` branch? Thanks!

Thanks! Just added the missing annotations and I moved the base to master.

**Comment by ezimanyi** [comment]
One last thing---looks like the unit tests failed.  I think it's just because of missing import statements for `com.netflix.spinnaker.halyard.config.model.v1.node.LocalFile` and `com.netflix.spinnaker.halyard.config.model.v1.node.SecretFile`.  If you fix that the tests should pass, and I'll merge this.  Thanks!

**Comment by sergedonaldp** [comment]
> One last thing---looks like the unit tests failed. I think it's just because of missing import statements for `com.netflix.spinnaker.halyard.config.model.v1.node.LocalFile` and `com.netflix.spinnaker.halyard.config.model.v1.node.SecretFile`. If you fix that the tests should pass, and I'll merge this. Thanks!

Just added them. Thanks!

**Comment by sergedonaldp** [comment]
Thanks!!!

**Pull request merged**
