### PR TITLE
feat(plugins): able to add plugin repositories

### PR DESCRIPTION
**Pull request by link108**
This PR enables configuring plugin repositories for PF4J to consume. See https://github.com/spinnaker/spinnaker/issues/5243 and https://github.com/pf4j/pf4j-update

### CODE REVIEW

**Comment by ezimanyi** [comment]
This looks reasonable (and maybe I'm missing this) but where are these settings actually used in the service configs?  (Or is that not part of this PR?)

**Comment by link108** [comment]
@ezimanyi This outputs the following to the service configs:
```
spinnaker:
  extensibility:
    repositories:
      my-repo-id:
        url: https://my.repo.url/
```

In each repository, there should be a file, `plugins.json` that describes the available plugins, see [pf4j-update's repository structure](https://github.com/pf4j/pf4j-update#repository-structure)


Do note, this is not sufficient for halyard supporting PF4J plugins, but is a stepping stone to get there. There will be another Halyard PR that will deprecate the previous plugin configurations and transition to only supporting PF4J plugins. This second PR will be a breaking change to whomever is using the MVP implementation of plugins, as Halyard will output plugin configurations for use with PF4J, not the MVP implementation.

**Comment by link108** [comment]
We discussed this in [slack](https://spinnakerteam.slack.com/archives/CK9FK4XDF/p1578510602005000) and then today in the Platform SIG meeting (see [agenda](https://docs.google.com/document/d/1zGIgEwO9lZfYaI0N6necuH-x0SjmL3hmbbeMWZgqnEw/edit#heading=h.n1w9jnw3t7un)). We will be producing another PR after this is merged to deploy a `plugin-manifest.json` for Deck to consume, while using PF4J-Update's repositories list to inform the backend services which plugins to install. This is an intermediary step for moving off of the MVP implementation, while Plugin Bundles and the Deck<->Front50 interactions are being built.

**Comment by link108** [comment]
@ezimanyi I updated the PR such that the hal config and the service configs are in the same format.

**Pull request merged**
