### PR TITLE
fix(halyard/macos): Catalina compability

### PR DESCRIPTION
**Pull request by jervi**
Halyard will not start on macOS Catalina because it can't write logs to `/var`. Changing the log directory to the user directory fixes the problem.

### CODE REVIEW

**Comment by german-muzquiz** [comment]
Did Catalina upgrade changed ownership of `/var/log/spinnaker` or is there another reason that Halyard cannot write to that dir? 
Logs folder reference is not just in hal startup script, there are other places in the code where we would need to change it that affect all operating systems: https://github.com/spinnaker/halyard/blob/master/halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/local/LocalLogCollectorFactory.java#L62.

**Comment by jervi** [comment]
No, the upgrade cleaned up the entire `/var` directory and moved everything "foreign" there into a "Relocated Items" folder in `/Users/Shared`. So there is no `/var/log/spinnaker` folder anymore. I can recreate it though.

I'm not arguing that the solution in this PR is the best solution, but maybe we could check in the startup script if the folder exist and if not, recreate it?

**Comment by german-muzquiz** [comment]
Creating the folder at startup if it doesn't exist sounds good. @ezimanyi thoughts?

**Comment by jervi** [comment]
On second thought, then we would need to run halyard as root. Maybe just a check and a better error message would suffice

**Comment by ethanfrogers** [comment]
FWIW, looks like this affects anyone doing any local development on Catalina, we well. I was testing another PR and, when running a `hal config` command, saw errors about not being able to save a temporary config file.

**Comment by german-muzquiz** [comment]
How about checking if the directories exist and if not, create them and set permissions with `sudo`, so that `hal` command would automatically ask for root password only in that case, something like this:
```
if [ ! -d "/var/log/spinnaker" ]
then
  sudo mkdir -p /var/log/spinnaker/halyard
  ....
fi
```

**Comment by ezimanyi** [comment]
I think the solution in the last comment above (checking if it exists, and creating it if not) makes sense.

**Pull request closed without merging**
