### PR TITLE
(cli) refactor UI

### PR DESCRIPTION
**Pull request by lwander**
@ewiseblatt @ttomsu PTAL

### CODE REVIEW

**Comment by lwander** [comment]
Build is failing because java home is set incorrectly :confused:... looking now

**Comment by ttomsu** [comment]
LGTM

**Comment by lwander** [comment]
@ewiseblatt I added the AnsiMessageBuilder (although a little differently from what you recommended). I prefer to keep the printing logic outside of the messages because it feels strange and locks us into always printing to stdout, when instead we could write many printers conforming to our AnsiPrinterInterface if we just pass the messages to them.

**Comment by ewiseblatt** [comment]
The "Style" change over Weight was still an improvement. I'd keep that.

**Comment by lwander** [comment]
Agreed

**Comment by lwander** [comment]
Good to go?

**Comment by ewiseblatt** [comment]
sure

**Pull request merged**
