### PR TITLE
Revert "config(core): Remove MPTV2 UI feature flag (#1510)"

### PR DESCRIPTION
**Pull request by louisjimenez**
This reverts commit 759e98840f7d67ec5b2e692a51cb6d8d0cadef56.

### CODE REVIEW

**Comment by louisjimenez** [comment]
Reverting this until Spinnaker 1.19 is released so that users can continue to use halyard to enable the mptv2 feature flag

**Comment by maggieneterval** [comment]
Is this because your PR that removed the flag from Deck didn't make it into 1.18?

**Comment by louisjimenez** [comment]
@maggieneterval That's right, the Deck PR targets 1.19 and onwards

**Comment by louisjimenez** [comment]
@spinnakerbot cherry-pick 1.31

**Pull request merged**
