### PR TITLE
feat(deployments): Update component sizing command to allow container…

### PR DESCRIPTION
**Pull request by mtweten**
… component sizing.

This adds the ability to set microservice container sizing (requests/limits) in addition to pod sizing. Generally the sidecar containers (e.g. monitoring) don't need the same sizing constraints as the main container.

### CODE REVIEW

**Comment by bnutt** [comment]
+1 this, I removed setting the monitoring sidecar due to not being able to set the individual limits for the containers.

**Comment by costimuraru** [comment]
lgtm

**Comment by bnutt** [comment]
@mtweten could this be rebased with master so we can get it merged in?

**Comment by mtweten** [comment]
Done!

**Comment by bnutt** [comment]
@costimuraru could this be merged in at your convenience?

**Comment by costimuraru** [comment]
@bnutt I'm not an approver, but perhaps @ethanfrogers could help us here?

**Pull request merged**
