### PR TITLE
Google-specific rosco commands added

### PR DESCRIPTION
**Pull request by lwander**
@duftler

### CODE REVIEW

**Comment by duftler** [comment]
I got this while testing:
```
$ ./hal config provider google bakery base-image list --no-validate
! ERROR Can not construct instance of
  com.netflix.spinnaker.halyard.config.model.v1.node.BakeryDefaults: abstract
  types either need to be mapped to concrete types, have custom deserializer, or
  contain additional type information
 at [Source: N/A; line: -1, column: -1]
```

**Comment by duftler** [comment]
Shouldn't I see an `add` subcommand listed here?
```
$ ./hal config provider google bakery base-image --help
BASE-IMAGE

  Manage and view Spinnaker configuration for the google provider's base
  image.

USAGE

  hal config provider google bakery base-image [parameters] [subcommands]

GLOBAL PARAMETERS

  -c, --color
    Enable terminal color output.

  -d, --debug
    Show detailed network traffic with halyard daemon.

  -h, --help=false
    Display help text about this command.

PARAMETERS

  --no-validate=false
    Skip validation.

SUBCOMMANDS

  delete
    Delete a specific google base image by name.

  get
    Get the specified base image details for the google provider.

  list
    List the base image names for the google provider.
```

**Comment by lwander** [comment]
No, I didn't have time to add those before I took off

**Comment by lwander** [comment]
The `add` & `edit` commands are the abstract base classes to be extended with parameters for each of the providers that support images. I'll fix that deserialization issue now

**Comment by lwander** [comment]
I added `add` & `edit` to Google, I'll update the bug with what's left

**Pull request merged**
