### PR TITLE
feat(artifacts): Add support for helm/chart artifacts

### PR DESCRIPTION
**Pull request by eromanova**
Issue: spinnaker/spinnaker#3284

### CODE REVIEW

**Comment by eromanova** [comment]
@spinnaker/reviewers review, please

**Comment by jfillo** [comment]
I'm not an official reviewer, but I think there should be some changes to allow the Halyard CLI to manage this configuration.

See
- https://github.com/spinnaker/halyard/blob/master/docs/commands.md#hal-config-artifact
- https://github.com/spinnaker/halyard/blob/master/halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/ArtifactProviderCommand.java
and whatever additional code paths need to be followed.

Also - features like this should also include a PR to update the official documentation. https://www.spinnaker.io/setup/artifacts/

**Comment by eromanova** [comment]
Thank you for review, guys @ezimanyi @jfillo. I added halyard cli support for helm artifact acconts and provided small changes according to @ezimanyi comment. Docs are also updated.

**Comment by ezimanyi** [comment]
@eromanova : Looks great, thanks for the changes.

**Pull request merged**
