### PR TITLE
AWS config

### PR DESCRIPTION
**Pull request by lwander**
https://github.com/spinnaker/halyard/issues/116

@duftler PTAL

@gardleopard PTAL

### CODE REVIEW

**Comment by lwander** [comment]
This is missing any sort of validation (this is where I'll need help from someone with more AWS knowledge than me)

**Comment by gardleopard** [comment]
I tested this a little bit now. Clouddriver would not accept the generated account config.

 
my working clouddriver-local.yml
```
  - accountId: "01337"
    discovery: "http://{{region}}.eureka.url.to.use:8080/eureka-server/v2"
    name: leet-aws-account
    regions:
    - {name: eu-west-1}
```
.halyard/clouddriver.yml
```
  - name: leet-aws-account
    defaultKeyPair: null
    edda: null
    discovery: http://{{region}}.eureka.url.to.use:8080/eureka-server/v2
    accountId: '01337'
    regions:
    - eu-west-1
```

.hal/config
```
      - name: leet-aws-account
        defaultKeyPair: null
        edda: null
        discovery: http://{{region}}.eureka.url.to.use:8080/eureka-server/v2
        accountId: '01337'
        regions:
        - eu-west-1
```

generated with:
```
./halyard-cli/bin/halyard-cli config provider aws account add infra-del-sndbx-test --accountId 01337  --regions eu-west-1 --discovery "http://{{region}}.eureka.eureka.url.to.use:8080/eureka-server/v2"
```

**Comment by gardleopard** [comment]
the doc for discovery should probably have a mention about `http://{{region}}.eureka.url.to.use:8080/eureka-server/v2`, because region is magic in this context.
```
--discovery
    The endpoint your Eureka discovery system is reachable at. See
    https://github.com/Netflix/eureka for more information.
```

**Comment by lwander** [comment]
Please try the add account command again, the `region` field structure was wrong.

**Comment by lwander** [comment]
What do you suggest the help text should be for the discovery param?

**Comment by gardleopard** [comment]
Im not sure what the help text should be. Could add something like:
`Example: http://{{region}}.eureka.url.to.use:8080/eureka-server/v2 {{region}} will make spinnaker use regions in the hostname while accessing discovery so that you can have discovery for multiple regions`

**Comment by lwander** [comment]
Sounds good, updated.

**Comment by lwander** [comment]
awshelp

**Comment by gardleopard** [comment]
The config worked now. I nuked .hal/config, set up the aws account, generated config and copied the `accounts:` list to our clouddriver instance. I tried with two accounts and it works.

**Pull request merged**
